### ISSUE TITLE
密码是啥啊，我不会解密

### ISSUE THREAD

**Issue by wudidewo13** [weiran1999/seckillcloud#5]
![image](https://user-images.githubusercontent.com/73993524/181790253-15a715dc-806d-4d00-8f3f-14af6d9f589a.png)

**Comment by weiran1999** [comment]
普通admin是admin 超级admin密码是super_admin

**Comment by weiran1999** [comment]
密码是 123

**Comment by weiran1999** [comment]
你好，我在GitHub上回复123是正确的吗





------------------ 原始邮件 ------------------
发件人: 半人半鬼，神枪第一燕双鹰 ***@***.***&gt;
发送时间: 2022年7月29日 23:13
收件人: weiran1999/seckillcloud ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [weiran1999/seckillcloud] 密码是啥啊，我不会解密 (Issue #5)

**Comment by wudidewo13** [comment]
可以的，我好久之前不看了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiran1999/seckillcloud"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月11日(星期二) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [weiran1999/seckillcloud] 密码是啥啊，我不会解密 (Issue #5)





 你好，我在GitHub上回复123是正确的吗 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 半人半鬼，神枪第一燕双鹰 ***@***.***&amp;gt; 
 发送时间: 2022年7月29日 23:13 
 收件人: weiran1999/seckillcloud ***@***.***&amp;gt; 
 抄送: Subscribed ***@***.***&amp;gt; 
 主题: Re: [weiran1999/seckillcloud] 密码是啥啊，我不会解密 (Issue #5)
